/* What's new: plain-English notes, newest first. Add one entry per version. */
const NEWS = [
  { v: 'v86', items: ['New form: Boiler commissioning checklist for a new boiler installation. It records compliance and Boiler Plus options, water quality, operating readings, condensate, combustion readings and customer handover, and makes a PDF in the same look as your other certificates. There is a price for it in Settings.'] },
  { v: 'v85', items: ['The gas rate calculator now starts blank on each new certificate, so the readings from the last job are not left in the boxes.'] },
  { v: 'v84', items: ['Defects: one-tap N/A, None taken or Customer advised under Remedial action taken (and N/A under a Legionella recommendation), so you do not have to type when there is nothing to say.'] },
  { v: 'v83', items: ['The Tools button in the bottom bar now has a spanner icon.'] },
  { v: 'v82', items: ['Tools now has its own button in the bottom bar, between Invoices and Settings. It disappears if you turn all the tools off in Settings.'] },
  { v: 'v81', items: ['Tools report: tick which calculator results go in the PDF, with Select all and Select none. Saved reports and the PDF only include what is ticked.'] },
  { v: 'v80', items: ['A fresh look: new OMB flame logo and icon, cleaner type, and a more polished feel throughout. Everything works the same.'] },
  { v: 'v79', items: ['Customer card: each property address now has its own address box and postcode box, with an Add another property button (and Remove).'] },
  { v: 'v78', items: ['Tools: opening Tools from the front page no longer shows the last customer you used it for.'] },
  { v: 'v77', items: ['Pipe sizing now uses the published BS 6891 copper pipe capacity table (interpolated between lengths) instead of a fitted formula. Sizes and the step-down figures are now on the safe side of the table.'] },
  { v: 'v76', items: ['Tools: a Show workings out button on each calculator, so you can follow every step of the sums.','Pipe sizing now divides your kW by 10.6 for the gas rate, and its pressure drop on larger pipes is fitted to the reference app.'] },
  { v: 'v75', items: ['Gas pipe sizing now shows how many metres of the bigger pipe you need nearest the meter before the rest of the run can drop a size.'] },
  { v: 'v74', items: ['Tools report: search for the customer, pick their property from a list, and tap Open report once the PDF is made.'] },
  { v: 'v73', items: ['The Tools button on the home screen now matches the other buttons.'] },
  { v: 'v72', items: ['Open a customer and tap Tools and calculation report. Their name, phone, email and property go at the top of the PDF report, and Same property is ticked for you. You can save the results on their card and open the PDF again later.'] },
  { v: 'v71', items: ['Tools: tick Same property and results carry from one calculator to the next (gas rate or heat loss into pipe sizing, pipe sizing into the tightness test).','Tools: create a PDF report of everything you have calculated, with your details and the customer at the top.'] },
  { v: 'v70', items: ['New tool: Tightness test volume. Works out the installation volume and the pressure drop allowed under the new IGEM/UP/1B Edition 4 rules that start on 1 October 2026.'] },
  { v: 'v69', items: ['You can now hide any of the Tools you do not use, in Settings.'] },
  { v: 'v68', items: ['In Tools, tap the heart to pin a calculator to the top.'] },
  { v: 'v67', items: ['In Tools, the calculators you use most move to the top.'] },
  { v: 'v66', items: ['New Tools section on the home screen: gas rate calculator, gas pipe sizing, and room-by-room heat loss with radiator sizes that change with your flow and return temperatures.','Customer search now finds invoice numbers and certificate numbers too.'] },
  { v: 'v65', items: ['The line on Annual checks due now reads "Reminder sent by email" instead of "Emailed automatically".'] },
  { v: 'v64', items: ['Annual checks due now shows "Reminder sent by email" with the date when an automatic reminder has gone to a customer.'] },
  { v: 'v63', items: ['The Annual checks due page now says whether automatic emails are on, so you know if you need to send anything yourself.'] },
  { v: 'v62', items: ['Legionella risk assessments now appear in Annual checks due, and in the automatic reminder emails, using the next assessment date on the record.'] },
  { v: 'v61', items: ['The Annual checks due button on the home screen now matches the other buttons.'] },
  { v: 'v60', items: ['Automatic reminder emails. Turn them on in Settings and customers with an email address get a reminder about 8 weeks before their gas check or boiler service is due, and again at 2 weeks.', 'Replies come to your own email. Every email has an unsubscribe link, and you can switch it off for any customer.', 'Booked in, Not needed and Stop now sync between your devices and stop the automatic emails too.', 'Fixed: editing a customer no longer removes their favourite heart.'] },
  { v: 'v59', items: ['New: Annual checks due. A button on the Records screen lists gas safety checks and boiler services coming up, or overdue.', 'Tap Text, WhatsApp or Email and the reminder opens on your phone ready to send, using the customer’s details. Nothing is sent without you pressing send.', 'Mark each one Booked in or Not needed, or stop reminders for a property. Change the wording and how early they show in Settings.'] },
  { v: 'v58', items: ['Help guide added. Tap the ? at the top of any screen, or find it in Settings.', 'This What’s new list.', 'Invoices: start typing a client name and matching customers appear. Tap one to fill in their details.', 'Invoices: tap a saved property for that customer, or start typing an address to see saved ones.', 'Send feedback: report a fault, make a suggestion or ask a question from Settings or the Help guide.'] },
  { v: 'v57', items: ['The gas rate timer can now be started before any meter readings are entered.', 'Adding a line to an invoice no longer jumps to the bottom. You stay where you are and the new line is ready to type in.'] },
  { v: 'v56', items: ['You can now open and view an invoice PDF from a customer’s record and from the ready-to-send box, not just edit it.'] },
  { v: 'v55', items: ['Addresses no longer end up with double commas on invoices.', 'Every address now has its own postcode box.'] },
  { v: 'v54', items: ['Boiler service PDF: the flue gas line now says “See results below (Combustion Analyser Readings)”.'] },
  { v: 'v53', items: ['Boiler service PDF: the column once called “Failure details” is now “Further information”.'] },
  { v: 'v52', items: ['“Update app now” is more reliable. It clears the saved copy and loads the newest version.'] },
  { v: 'v51', items: ['The App version box and Update app now button are now at the top of Settings.'] },
  { v: 'v50', items: ['Boiler service: the system filter questions now come after the appliance checks, so the form flows better.'] },
  { v: 'v48', items: ['Backups can now be protected with a password.', 'Bank details are left out of backup files.'] },
  { v: 'v47', items: ['A monthly reminder to back up your data.'] },
  { v: 'v46', items: ['If your sign-up email does not arrive, there is now a resend button.'] }
];
function newsHtml(n) {
  return NEWS.slice(0, n || NEWS.length).map(x => `<div class="card"><div class="t" style="margin-bottom:6px">${x.v}</div><ul style="margin:0;padding-left:20px">${x.items.map(i => `<li style="margin-bottom:6px">${i}</li>`).join('')}</ul></div>`).join('');
}
